compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
