compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32
