name: 'Release Notes (Drafter)'

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency:
  group: drafter-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_draft_release:
    # We need to not re-run this when we commit during the release process.
    if: "!contains(github.event.head_commit.message, '[release]: ')"
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
